#! /bin/sh


# echo "deb [trusted=yes] https://repo.nxos.org stable" >> /etc/apt/sources.list

cp () {
    scp "$1" "$remote:/tmp/"
    ssh "$remote" reptile cp "/tmp/${1##*/}" "$2"
    ssh "$remote" rm "/tmp/${1##*/}"
}

[ $# -gt 0 ] && remote="$1" && shift

case "$1" in
    cp ) "$@";;
    mk | mv | rm | ls ) ssh "$remote" reptile "$@";;

    * )
        echo "Usage: boa <remote> <command [args]>"
        echo ""
        echo "command is any of:"
        echo ""
        echo "  mk <repo>             Create a new repository."
        echo "  cp <pkg> <repo>       Add a package to a repository."
        echo "  rm <repo> [pkg]       Remove a repository or package that belongs to a repository."
        echo "  mv <pkg> <from> <to>  Move a package from a repository to another."
        echo "  mv <old> <new>        Rename a repository."
        echo "  ls [repo] [pkg]       List the contents of a repository or a package. If no"
        echo "                        arguments are provided, list all repositories.";;
esac
