#! /bin/sh


index () { for r; do dpkg-scanpackages "$r" | gzip -9c > "$r/Packages.gz"; done; }

echo "$*" | grep -F '../' \
    && echo 'Relative file names are not allowed.' \
    && exit 1

mkdir -p /var/reptile
cd /var/reptile


x="$1"; shift

case "$x" in
    mk ) mkdir -p "$@";;

    mv ) case $# in
         ( 2 ) mv "$1" "$2";;
         ( 3 ) mv "$2/$1" "$3"; index "$2" "$3";; esac;;

    cp ) r="$1"; shift
         for p; do rm -f "$r/`basename ${p%%_*}`"*; done
         cp "$@" "$r"
         index "$2";;

    rm ) case $# in
         ( 0 ) ;;
         ( 1 ) rm -rf "$1";;
         ( * ) r="$1"; shift
               for p; do rm -f "$r/$p"; done
               index "$1";; esac;;

    ls ) case $# in
         ( 0 ) ls -1;;
         ( 1 ) ls -1 "$1";;
         ( 2 ) dpkg --contents "$1/$2"*;; esac;;
esac
