#! /bin/sh -x


index () { for repo; do dpkg-scanpackages "$repo" | gzip -9c > "$repo/Packages.gz"; done; }

echo "$*" | grep -F '../' \
    && echo 'Relative file names are not allowed. Aborting.' \
    && exit 1

mkdir -p /var/reptile
cd /var/reptile


x="$1"; shift
case "$x" in
    cp ) rm -f "$2/`basename "${1%%_*}"`"* && cp "$1" "$2" && index "$2";;

    mk ) mkdir -p "$1";;

    mv ) [ $# = 3 ] && mv "$1" "$2"
         [ $# = 4 ] && mv "$2/$1" "$3" && index "$2" "$3";;

    rm ) [ $# = 2 ] && rm -rf "$1"
         [ $# = 2 ] && rm -f "$1/$2" && index "$1";;

    ls ) [ $# = 0 ] && ls -1
         [ $# = 1 ] && ls -1 "$1"
         [ $# = 2 ] && dpkg --contents "$1/$2";; esac
